### PR TITLE
Sticky Navigation fix

### LINKED ISSUE #100: Update Sticky navigation look as original
Screenshot 2023-08-04 at 15 05 07

### PR DESCRIPTION
**Pull request by andreibogdan**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #100

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/internet-security
- After: https://100-sticky-nav-fix--bitdefender--hlxsites.hlx.page/solutions/internet-security

### CODE REVIEW

**Comment by andreibogdan** [comment]
Screenshot 2023-08-04 at 16 39 37

**Comment by rhudea** [comment]
Something broke if you scroll over hero: 
image

**Comment by andreibogdan** [comment]
> Something broke if you scroll over hero: image

done

**Review by rhudea — APPROVED** [review]
Beside the already existing issue, this LGTM

**Comment by andreibogdan** [comment]
Opened a ticket regarding sticky nav and menu #105

**Pull request merged**
